POST {{url}}/api/v1/motorcycles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "model": "Titan 160cc ABS",
  "brand": "honda",
  "year": 2022,
  "daily_price": 38.99,
  "license_plate": "PIA-2A91"
}

> {% 
if (response.status === 200) {
  client.global.set('motorcycle_id', response.body.id);
}
%}