POST {{url}}/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "JohnDoe123",
  "given_name": "John",
  "family_name": "Doe",
  "birthdate": "2000-09-05",
  "cnpj": "18.864.014/0001-19",
  "cnh_number": "92353762700",
  "cnh_category": "ab",
  "cnh_exp_date": "2026-12-31"
}

> {% 
if (response.status === 201) {
  client.global.set('access_token', response.body.access_token);
}
%}