POST {{url}}/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "john@admin.com",
  "password": "John@123"
}

> {% 
if (response.status === 200) {
  client.global.set('access_token', response.body.access_token);
}
%}