global using System.Net;
global using System.Net.Http.Json;
global using FluentAssertions;
global using JetBrains.Annotations;
global using Microsoft.EntityFrameworkCore;
global using Motorent.Api.IntegrationTests.TestUtils;
global using Motorent.Api.IntegrationTests.TestUtils.Fixtures;
global using Motorent.Api.IntegrationTests.TestUtils.Requests;
global using Motorent.TestUtils.Factories;