// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motorent.Infrastructure.Common.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Motorent.Infrastructure.Common.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240601120018_AddRenterRentalIds")]
    partial class AddRenterRentalIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Motorent.Domain.Motorcycles.Motorcycle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_motorcycles");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_motorcycles_license_plate");

                    b.ToTable("motorcycles", (string)null);
                });

            modelBuilder.Entity("Motorent.Domain.Rentals.Rental", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MotorcycleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("motorcycle_id");

                    b.Property<decimal>("Penalty")
                        .HasColumnType("numeric")
                        .HasColumnName("penalty");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<string>("RenterId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("renter_id");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rentals");

                    b.ToTable("rentals", (string)null);
                });

            modelBuilder.Entity("Motorent.Domain.Renters.Renter", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("document");

                    b.Property<string>("DriverLicenseImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("dl_image");

                    b.Property<string>("DriverLicenseStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dl_status");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_renters");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_renters_email");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_renters_user_id");

                    b.ToTable("renters", (string)null);
                });

            modelBuilder.Entity("Motorent.Infrastructure.Common.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("id");

                    b.Property<IDictionary<string, string>>("Claims")
                        .HasColumnType("jsonb")
                        .HasColumnName("claims");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("password_hash");

                    b.Property<string[]>("Roles")
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01HZ9TR1HYY83RTB891RY7BFAM",
                            Claims = new Dictionary<string, string> { ["given_name"] = "John", ["family_name"] = "Doe", ["birthdate"] = "2000-09-05" },
                            Email = "john@admin.com",
                            PasswordHash = "fh1kX6tZmXG1mSR9mj5BBf6wvOthfUH/kmyTUhffGaQ=:1iCcbD3NdzpPtoqdIqWb5w==:50000:SHA256",
                            Roles = new[] { "admin" }
                        });
                });

            modelBuilder.Entity("Motorent.Infrastructure.Common.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Motorent.Domain.Rentals.Rental", b =>
                {
                    b.OwnsOne("Motorent.Domain.Rentals.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<string>("RentalId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("start");

                            b1.HasKey("RentalId");

                            b1.ToTable("rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalId")
                                .HasConstraintName("fk_rentals_rentals_id");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("Motorent.Domain.Renters.Renter", b =>
                {
                    b.OwnsOne("Motorent.Domain.Renters.ValueObjects.DriverLicense", "DriverLicense", b1 =>
                        {
                            b1.Property<string>("RenterId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("dl_category");

                            b1.Property<DateOnly>("Expiry")
                                .HasColumnType("date")
                                .HasColumnName("dl_expiry");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("dl_number");

                            b1.HasKey("RenterId");

                            b1.HasIndex("Number")
                                .IsUnique()
                                .HasDatabaseName("ix_renters_driver_license_number");

                            b1.ToTable("renters");

                            b1.WithOwner()
                                .HasForeignKey("RenterId")
                                .HasConstraintName("fk_renters_renters_id");
                        });

                    b.OwnsOne("Motorent.Domain.Renters.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<string>("RenterId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<string>("FamilyName")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("family_name");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("given_name");

                            b1.HasKey("RenterId");

                            b1.ToTable("renters");

                            b1.WithOwner()
                                .HasForeignKey("RenterId")
                                .HasConstraintName("fk_renters_renters_id");
                        });

                    b.OwnsMany("Motorent.Domain.Rentals.ValueObjects.RentalId", "RentalIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("char(26)")
                                .HasColumnName("rental_id");

                            b1.Property<string>("renter_id")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("renter_id");

                            b1.HasKey("Id")
                                .HasName("pk_renter_rentals");

                            b1.HasIndex("renter_id")
                                .HasDatabaseName("ix_renter_rentals_renter_id");

                            b1.ToTable("renter_rentals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("renter_id")
                                .HasConstraintName("fk_renter_rentals_renters_renter_id");
                        });

                    b.Navigation("DriverLicense")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("RentalIds");
                });
#pragma warning restore 612, 618
        }
    }
}
